name: Matrix

on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [6,8,10]
    runs-on: ubuntu-latest
    steps:
      - name: Log Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log Node version
        run: node -v